### ISSUE TITLE
Part B: Queues (NoDupsDePrioritizeArrayQueue.java)

### ISSUE THREAD

**Issue by jchongm** [CS111C-META-FALL-2016/LabE-Team2#2]
**NoDupsDePrioritizeArrayQueue** is a subclass of **ArrayQueue**. The subclass disallows duplicate items in the queue.

We need to create 3 methods in the subclass:

- **public void enqueue(T newEntry)** // overrides parent class; will not add item if it exists already.
- **public void moveToBack(T entry)** // moves entry to back of queue; if nonexistent, add to queue.
- **public void display()** // prints queue, must indicate which side is FRONT and BACK.

Note that **ArrayQueue** is a circular array with one unused location. The front index changes with dequeues and the back index changes with enqueues. The arrays are expandable. The subclass has access to variables in the parent class.

Use **LabEPartBDriver** to test your code.

**Comment by dwgass** [comment]
Stoked to get to work in the AM. :)
